[package]
name = "waybg-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.0.1"

[dev-dependencies]
tempfile = "3.25.0"
