repos:
  - repo: local
    hooks:
      - id: zig-fmt-check
        name: zig fmt (check)
        language: system
        entry: zig build fmt-check
        pass_filenames: false
      - id: zig-ci
        name: zig ci
        language: system
        entry: zig build ci
        pass_filenames: false
