[package]
name = "waybg-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
waybg-core = { path = "../waybg-core" }
wayland-core = { path = "../wayland-core" }
