[package]
name = "wayland-core"
version = "0.1.0"
edition = "2024"

[dependencies]
gstreamer = "0.24.4"
libc = "0.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
smithay-client-toolkit = "0.20.0"
